//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.08 at 07:12:57 PM CEST 
//


package com.centralapi.domain.xml.xml_ftn.rooms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.centralapi.domain.xml.xml_ftn.users.RegistredUser;


/**
 * <p>Java class for RateAndComment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RateAndComment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rating">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;maxInclusive value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.xml-ftn.xml.domain.centralapi.com/Users}RegistredUser"/>
 *         &lt;element name="isAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RateAndComment", propOrder = {
    "comment",
    "rating",
    "registredUser",
    "isAllowed"
})
public class RateAndComment {

    @XmlElement(required = true)
    protected String comment;
    protected int rating;
    @XmlElement(name = "RegistredUser", namespace = "http://www.xml-ftn.xml.domain.centralapi.com/Users", required = true)
    protected RegistredUser registredUser;
    protected boolean isAllowed;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     */
    public int getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     */
    public void setRating(int value) {
        this.rating = value;
    }

    /**
     * Gets the value of the registredUser property.
     * 
     * @return
     *     possible object is
     *     {@link RegistredUser }
     *     
     */
    public RegistredUser getRegistredUser() {
        return registredUser;
    }

    /**
     * Sets the value of the registredUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistredUser }
     *     
     */
    public void setRegistredUser(RegistredUser value) {
        this.registredUser = value;
    }

    /**
     * Gets the value of the isAllowed property.
     * 
     */
    public boolean isIsAllowed() {
        return isAllowed;
    }

    /**
     * Sets the value of the isAllowed property.
     * 
     */
    public void setIsAllowed(boolean value) {
        this.isAllowed = value;
    }

}
