//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.16 at 03:13:49 AM CEST 
//


package com.example.demo.domain;


import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

public enum ReservationStateEnum {

    ALLOWED,
    NOTALLOWED,
    PENDING;

    public String value() {
        return name();
    }

    public static ReservationStateEnum fromValue(String v) {
        return valueOf(v);
    }

}
